// <auto-generated />
using System;
using Maliev.PricingService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Maliev.PricingService.Data.Migrations
{
    [DbContext(typeof(PricingDbContext))]
    partial class PricingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Maliev.PricingService.Data.Entities.PricingAuditRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CalculatedBySystem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<TimeSpan>("CalculationDuration")
                        .HasColumnType("interval");

                    b.Property<decimal>("ComplexitySurcharge")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ConfidenceLevel")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ConfigMachineHourlyRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ConfigMarginMultiplier")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ConfigMaterialPricePerCm3")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal>("ConfigSupportPricePerCm3")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("InputBoundingBoxX")
                        .HasColumnType("numeric");

                    b.Property<decimal>("InputBoundingBoxY")
                        .HasColumnType("numeric");

                    b.Property<decimal>("InputBoundingBoxZ")
                        .HasColumnType("numeric");

                    b.Property<bool>("InputIsManifold")
                        .HasColumnType("boolean");

                    b.Property<decimal>("InputSupportVolumeCm3")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal>("InputSurfaceAreaCm2")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<int>("InputTriangleCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("InputVolumeCm3")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("MLModelVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("MachineTimeCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("ManufacturingProcessId")
                        .HasColumnType("uuid");

                    b.Property<string>("ManufacturingProcessName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("MarginAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("MaterialCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("MaterialCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PricingConfigurationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid?>("QuotationId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("SetupCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Strategy")
                        .HasColumnType("integer");

                    b.Property<decimal>("SubtotalBeforeMargin")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("SupportMaterialCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotalUnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ValidUntil")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PricingConfigurationId");

                    b.ToTable("pricing_audit_records", (string)null);
                });

            modelBuilder.Entity("Maliev.PricingService.Data.Entities.PricingConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("ComplexitySurchargePercent")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ComplexityThreshold")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MachineHourlyRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("ManufacturingProcessId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("MarginMultiplier")
                        .HasColumnType("numeric");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("MaterialPricePerCm3")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal>("MinimumOrderPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PrintSpeedCm3PerHour")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version")
                        .HasDefaultValueSql("decode('0000000000000000', 'hex')");

                    b.Property<decimal>("SetupCostFlat")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SupportMaterialPricePerCm3")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId", "ManufacturingProcessId", "EffectiveFrom")
                        .IsUnique();

                    b.ToTable("pricing_configurations", (string)null);
                });

            modelBuilder.Entity("Maliev.PricingService.Data.Entities.PricingModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("DeployedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MeanAbsoluteError")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal>("MeanAbsolutePercentageError")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("ModelFilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ModelType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("RSquared")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTime?>("RetiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bytea")
                        .HasColumnName("row_version")
                        .HasDefaultValueSql("decode('0000000000000000', 'hex')");

                    b.Property<DateTime>("TrainingCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TrainingDataCount")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("TrainingDuration")
                        .HasColumnType("interval");

                    b.Property<DateTime>("TrainingStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("pricing_models", (string)null);
                });

            modelBuilder.Entity("Maliev.PricingService.Data.Entities.PricingSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CalculatedPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("InfillPercentage")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("LayerHeight")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ManualOverridePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("MaterialBrand")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("MaterialCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("PricingAuditRecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("PrintOrientation")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("QuotationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("SupersededById")
                        .HasColumnType("uuid");

                    b.Property<string>("SupportType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Technology")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("OrderId");

                    b.HasIndex("PricingAuditRecordId");

                    b.HasIndex("SupersededById")
                        .IsUnique();

                    b.ToTable("PricingSnapshots");
                });

            modelBuilder.Entity("Maliev.PricingService.Data.Entities.PricingTrainingData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("ActualLaborHours")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("ActualMaterialUsedCm3")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal?>("ActualPrintTimeHours")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("ActualProfitMargin")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("ActualTotalCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("CustomerAccepted")
                        .HasColumnType("boolean");

                    b.Property<bool>("JobCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("JobSucceeded")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PricingAuditRecordId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TrainedModelId")
                        .HasColumnType("uuid");

                    b.Property<bool>("UsedForTraining")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("PricingAuditRecordId")
                        .IsUnique();

                    b.HasIndex("TrainedModelId");

                    b.ToTable("pricing_training_data", (string)null);
                });

            modelBuilder.Entity("Maliev.PricingService.Data.Entities.PricingAuditRecord", b =>
                {
                    b.HasOne("Maliev.PricingService.Data.Entities.PricingConfiguration", "PricingConfiguration")
                        .WithMany()
                        .HasForeignKey("PricingConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PricingConfiguration");
                });

            modelBuilder.Entity("Maliev.PricingService.Data.Entities.PricingSnapshot", b =>
                {
                    b.HasOne("Maliev.PricingService.Data.Entities.PricingAuditRecord", "PricingAuditRecord")
                        .WithMany()
                        .HasForeignKey("PricingAuditRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Maliev.PricingService.Data.Entities.PricingSnapshot", "SupersededBy")
                        .WithOne()
                        .HasForeignKey("Maliev.PricingService.Data.Entities.PricingSnapshot", "SupersededById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PricingAuditRecord");

                    b.Navigation("SupersededBy");
                });

            modelBuilder.Entity("Maliev.PricingService.Data.Entities.PricingTrainingData", b =>
                {
                    b.HasOne("Maliev.PricingService.Data.Entities.PricingAuditRecord", "PricingAuditRecord")
                        .WithOne("TrainingData")
                        .HasForeignKey("Maliev.PricingService.Data.Entities.PricingTrainingData", "PricingAuditRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Maliev.PricingService.Data.Entities.PricingModel", "TrainedModel")
                        .WithMany()
                        .HasForeignKey("TrainedModelId");

                    b.Navigation("PricingAuditRecord");

                    b.Navigation("TrainedModel");
                });

            modelBuilder.Entity("Maliev.PricingService.Data.Entities.PricingAuditRecord", b =>
                {
                    b.Navigation("TrainingData");
                });
#pragma warning restore 612, 618
        }
    }
}
